env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
rules: {
  camelcase: off,
  semi: [1, "always"],
  quotes: [1, "double"],
  max-len: [1, { code: 120 }],
  indent: [1, "tab"],
  no-tabs: 0,
}
